services:
  db:
    image: postgres:18.0
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres #Replace me
      POSTGRES_USER: postgres #Replace me
      POSTGRES_DB: postgres #Replace me
    ports:
      - 5432:5432 # do not expose on servers

volumes:
  postgres_data:
